//关于登录的actionTypes
export const USER_LOGIN_START="USER/LOGIN/START";
export const USER_LOGIN_SUCCESS="USER/LOGIN/SUCCESS";
export const USER_LOGIN_FAIL="USER/LOGIN/FAIL";
export const USER_LOGIN_BEFORE_SUCCESS="USER/LOGIN/BEFORE/SUCCESS";
//关于注册的actionTypes
export const USER_REGISTER_START="USER/REGISTER/START";
export const USER_REGISTER_SUCCESS="USER/REGISNTER/SUCCESS";;
export const USER_REGISTER_FAIL="USER/REGISTER/FAIL";
//关于注销的actionTypes
export const USER_LOGOUT_START="USER/LOGOUT/START";
export const USER_LOGOUT_SUCCESS="USER/LOGOUT/SUCCESS";
export const USER_LOGOUT_FAIL="USER/LOGOUT/FAIL";