//定义login状态
export const LOGIN_STATUS_START="LOGIN/STATUS/START";
export const LOGIN_STATUS_SUCCESS="LOGIN/STATUS/SUCCESS";
export const LOGIN_STATUS_BEFORE_SUCCESS="LOGIN/STATUS/BEFORE/SUCCESS";
export const LOGIN_STATUS_FAIL="LOGIN/STATUS/FAIL";
export const LOGIN_STATUS_NOT_START="LOGIN/STATUS/NOT/START"