export const TOGGLE_HEADER_STATUS_NONE="TOGGLE/STATUS/NONE";
export const TOGGLE_HEADER_STATUS_LOGIN="TOGGLE/STATUS/LOGIN";
export const TOGGLE_HEADER_STATUS_REGISTER="TOGGLE/STATUS/REGISTER";
export const TOGGLE_HEADER_STATUS_LOGOUT="TOGGLE/STATUS/LOGOUT";