export const HEADER_VIEW_STATUS_NONE="HEADER/VIEW/STATUS/NONE";
export const HEADER_VIEW_STATUS_LOGIN="HEADER/VIEW/STATUS/LOGIN";
export const HEADER_VIEW_STATUS_REGISTER="HEADER/VIEW/STATUS/REGISTER";
export const HEADER_VIEW_STATUS_LOGOUT="HEADER/VIEW/STATUS/LOGOUT";